# Generated by Django 3.2.5 on 2021-08-02 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qa_mgt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='q_paper',
            field=models.CharField(default='this', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_paper', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('total_score', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResposeBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('Option 1', 'option1'), ('Option 2', 'option2'), ('Option 3', 'option3'), ('Option 4', 'option4')], max_length=10)),
                ('score', models.IntegerField(default=0)),
                ('answered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa_mgt.questionbank')),
            ],
        ),
    ]
