# Generated by Django 3.2.5 on 2021-08-04 21:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qa_mgt', '0002_auto_20210802_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionbank',
            name='setter',
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(default=datetime.time(0, 30))),
                ('no_of_ques', models.PositiveIntegerField(default=5)),
                ('setter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='q_paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa_mgt.questionpaper'),
        ),
        migrations.AlterField(
            model_name='userscore',
            name='q_paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa_mgt.questionpaper'),
        ),
    ]
